# fly.toml app configuration file generated for watts-for-dinner on 2026-10-04T12:10:39-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'watts-for-dinner'
primary_region = 'sjc'

[build]
  dockerfile = 'Dockerfile'

[build.args]
  VITE_POSTHOG_KEY="phc_CywFDxUNDhcq4V7VFH2dBNYP7awosbXZUUcjU2ZBnKi6"
  VITE_POSTHOG_HOST="https://us.i.posthog.com"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
