/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as ApiWhoopCallbackRouteImport } from './routes/api/whoop/callback'
import { Route as ApiWhoopConnectRouteImport } from './routes/api/whoop/connect'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWhoopCallbackRoute = ApiWhoopCallbackRouteImport.update({
  id: '/api/whoop/callback',
  path: '/api/whoop/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWhoopConnectRoute = ApiWhoopConnectRouteImport.update({
  id: '/api/whoop/connect',
  path: '/api/whoop/connect',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/api/chat': typeof ApiChatRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/api/whoop/callback': typeof ApiWhoopCallbackRoute
  '/api/whoop/connect': typeof ApiWhoopConnectRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/api/chat': typeof ApiChatRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/api/whoop/callback': typeof ApiWhoopCallbackRoute
  '/api/whoop/connect': typeof ApiWhoopConnectRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/api/chat': typeof ApiChatRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/api/whoop/callback': typeof ApiWhoopCallbackRoute
  '/api/whoop/connect': typeof ApiWhoopConnectRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/api/chat'
    | '/onboarding/'
    | '/api/whoop/callback'
    | '/api/whoop/connect'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/api/chat'
    | '/onboarding'
    | '/api/whoop/callback'
    | '/api/whoop/connect'
  id:
    | '__root__'
    | '/'
    | '/privacy'
    | '/api/chat'
    | '/onboarding/'
    | '/api/whoop/callback'
    | '/api/whoop/connect'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyRoute: typeof PrivacyRoute
  ApiChatRoute: typeof ApiChatRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
  ApiWhoopCallbackRoute: typeof ApiWhoopCallbackRoute
  ApiWhoopConnectRoute: typeof ApiWhoopConnectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/whoop/callback': {
      id: '/api/whoop/callback'
      path: '/api/whoop/callback'
      fullPath: '/api/whoop/callback'
      preLoaderRoute: typeof ApiWhoopCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/whoop/connect': {
      id: '/api/whoop/connect'
      path: '/api/whoop/connect'
      fullPath: '/api/whoop/connect'
      preLoaderRoute: typeof ApiWhoopConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyRoute: PrivacyRoute,
  ApiChatRoute: ApiChatRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
  ApiWhoopCallbackRoute: ApiWhoopCallbackRoute,
  ApiWhoopConnectRoute: ApiWhoopConnectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
